// One-off: rename the new site's page URLs to exactly match the old WordPress
// site's URLs. Replaces quoted internal references ("/met-con" -> "/classes/met-con")
// across code + data. Folder moves (git mv) and next.config redirects are handled
// separately. seo-overrides.json is regenerated by migrate-seo.mjs, and next.config.ts
// / scripts/ are intentionally NOT touched here.

import fs from "fs";
import path from "path";

// new clean URL -> old-site URL
const MAP = {
  "/about": "/about-us",
  "/contact": "/contact-us",
  "/allied-health": "/allied-health-staff",
  "/athlete-programs": "/athletes-program",
  "/membership": "/memberships",
  "/met-con": "/classes/met-con",
  "/mat-pilates": "/classes/mat-pilates",
  "/mobility": "/classes/mobility",
  "/hiit-push-and-drag": "/classes/hiit-push-and-drag",
  "/lift": "/classes/weightlifting",
  "/youth-agility-development": "/classes/youth-agility-development",
  "/youth-agility-foundations": "/classes/youth-agility-foundations",
  "/youth-fitness-development": "/classes/youth-fitness-development",
  "/youth-fitness-foundations": "/classes/youth-fitness-foundations",
  "/youth-speed-development": "/classes/youth-speed-development",
  "/youth-speed-foundation": "/classes/youth-speed-foundation",
};

const ROOTS = ["app", "components", "lib", "data"];
const EXCLUDE_FILES = new Set([
  "data/seo-overrides.json",
  "seo-export-raw.json",
]);
const ALLOW_EXT = new Set([".ts", ".tsx", ".json"]);

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name).replace(/\\/g, "/");
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".next") continue;
      walk(p, out);
    } else if (ALLOW_EXT.has(path.extname(entry.name)) && !EXCLUDE_FILES.has(p)) {
      out.push(p);
    }
  }
  return out;
}

const files = ROOTS.flatMap((r) => (fs.existsSync(r) ? walk(r) : []));
let totalFiles = 0;
let totalHits = 0;

for (const file of files) {
  let src = fs.readFileSync(file, "utf8");
  let hits = 0;
  for (const [clean, old] of Object.entries(MAP)) {
    // Match the URL only as a complete quoted token: "/met-con" (not "/met-con-x"
    // or "/classes/met-con"). The closing quote guarantees an exact path.
    const needle = `"${clean}"`;
    const replacement = `"${old}"`;
    const parts = src.split(needle);
    if (parts.length > 1) {
      hits += parts.length - 1;
      src = parts.join(replacement);
    }
  }
  if (hits) {
    fs.writeFileSync(file, src);
    totalFiles++;
    totalHits += hits;
    console.log(`${String(hits).padStart(3)}  ${file}`);
  }
}

console.log(`\nUpdated ${totalHits} references across ${totalFiles} files.`);
